import csv

# Sample office data (tourism boards, embassies, government offices, etc.)
data = [
    ["office_id", "Continent", "Country", "Region", "City", "Name", "Type", "Info", "Description", "Website", "Address", "Facebook", "Instagram", "LinkedIn", "X", "YouTube", "Email", "Phone", "Logo", "Background_Image", "Google_Maps_Link"],
    ["OF001", "North America", "USA", "California", "Los Angeles", "Visit California", "Tourism Board", "Official tourism board of California", "Promoting tourism and attractions across California", "https://www.visitcalifornia.com", "555 Capitol Mall, Suite 1100, Sacramento, CA 95814", "https://facebook.com/visitcalifornia", "https://instagram.com/visit_california", "https://linkedin.com/company/visit-california", "https://twitter.com/VisitCA", "https://youtube.com/visitcalifornia", "info@visitcalifornia.com", "+1-916-444-4429", "https://www.visitcalifornia.com/logo.png", "https://www.visitcalifornia.com/bg.jpg", "https://maps.google.com/?q=38.5767,-121.4934"],
    ["OF002", "Europe", "Germany", "Bavaria", "Munich", "Munich Tourism Office", "Tourism Board", "Official Munich tourist information", "Discover Munich's culture, history, and attractions", "https://www.muenchen.de/en", "Sendlinger Str. 1, 80331 München", "https://facebook.com/muenchen", "https://instagram.com/muenchen", "https://linkedin.com/company/muenchen", "https://twitter.com/Muenchen_de", "https://youtube.com/muenchen", "tourismus@muenchen.de", "+49-89-233-96500", "https://www.muenchen.de/logo.svg", "https://www.muenchen.de/bg.jpg", "https://maps.google.com/?q=48.1351,11.5820"],
    ["OF003", "Asia", "Japan", "Kanto", "Tokyo", "Japan National Tourism Organization", "Tourism Board", "Official tourism organization of Japan", "Promoting travel to Japan worldwide", "https://www.jnto.go.jp", "2-10-1 Yurakucho, Chiyoda-ku, Tokyo", "https://facebook.com/visitjapan", "https://instagram.com/visitjapanjp", "https://linkedin.com/company/jnto", "https://twitter.com/JapanTravel", "https://youtube.com/visitjapan", "info@jnto.go.jp", "+81-3-3216-1901", "https://www.jnto.go.jp/logo.png", "https://www.jnto.go.jp/bg.jpg", "https://maps.google.com/?q=35.6762,139.7633"],
    ["OF004", "North America", "USA", "District of Columbia", "Washington", "US Embassy Paris", "Embassy", "United States Embassy in France", "Diplomatic mission representing the USA in France", "https://fr.usembassy.gov", "2 Avenue Gabriel, 75008 Paris, France", "https://facebook.com/USEmbassyParis", "https://instagram.com/usembassyparis", "https://linkedin.com/company/us-embassy-paris", "https://twitter.com/USEmbassyFrance", "", "ParisACS@state.gov", "+33-1-43-12-22-22", "https://fr.usembassy.gov/logo.png", "https://fr.usembassy.gov/bg.jpg", "https://maps.google.com/?q=48.8698,2.3137"],
    ["OF005", "Europe", "France", "Île-de-France", "Paris", "Paris Convention and Visitors Bureau", "Tourism Board", "Official Paris tourism office", "Promoting Paris as a premier tourist destination", "https://en.parisinfo.com", "25 Rue des Pyramides, 75001 Paris", "https://facebook.com/ParisJeTaime", "https://instagram.com/parisjetaime", "https://linkedin.com/company/paris-convention-and-visitors-bureau", "https://twitter.com/ParisJeTaime", "https://youtube.com/parisjetaime", "info@parisinfo.com", "+33-1-49-52-42-63", "https://en.parisinfo.com/logo.svg", "https://en.parisinfo.com/bg.jpg", "https://maps.google.com/?q=48.8566,2.3522"],
    ["OF006", "Asia", "UAE", "Dubai", "Dubai", "Dubai Tourism", "Tourism Board", "Official Dubai tourism authority", "Showcasing Dubai's world-class attractions", "https://www.visitdubai.com", "Emirates Towers, Sheikh Zayed Road, Dubai", "https://facebook.com/visitdubai", "https://instagram.com/visitdubai", "https://linkedin.com/company/dubai-tourism", "https://twitter.com/visitdubai", "https://youtube.com/visitdubai", "info@dubaitourism.ae", "+971-4-282-1111", "https://www.visitdubai.com/logo.png", "https://www.visitdubai.com/bg.jpg", "https://maps.google.com/?q=25.2048,55.2708"],
    ["OF007", "Oceania", "Australia", "New South Wales", "Sydney", "Destination NSW", "Tourism Board", "Official NSW tourism organization", "Promoting tourism in New South Wales", "https://www.destinationnsw.com.au", "Level 2, 88 Cumberland St, The Rocks NSW 2000", "https://facebook.com/DestinationNSW", "https://instagram.com/visitnsw", "https://linkedin.com/company/destination-nsw", "https://twitter.com/VisitNSW", "https://youtube.com/visitnsw", "info@dnsw.com.au", "+61-2-9931-1111", "https://www.destinationnsw.com.au/logo.png", "https://www.destinationnsw.com.au/bg.jpg", "https://maps.google.com/?q=-33.8688,151.2093"],
    ["OF008", "Africa", "Kenya", "Nairobi Region", "Nairobi", "Kenya Tourism Board", "Tourism Board", "Official tourism board of Kenya", "Promoting Kenya's wildlife and cultural tourism", "https://www.magicalkenya.com", "Kenya-Re Towers, Upper Hill, Nairobi", "https://facebook.com/MagicalKenya", "https://instagram.com/magicalkenya", "https://linkedin.com/company/kenya-tourism-board", "https://twitter.com/MagicalKenya", "https://youtube.com/magicalkenya", "info@ktb.go.ke", "+254-20-271-1262", "https://www.magicalkenya.com/logo.png", "https://www.magicalkenya.com/bg.jpg", "https://maps.google.com/?q=-1.2921,36.8219"],
    ["OF009", "South America", "Brazil", "São Paulo", "São Paulo", "Visit Brasil", "Tourism Board", "Brazilian Tourism Board", "Promoting Brazil's diverse tourism offerings", "https://www.visitbrasil.com", "Rua Uruguaiana, 174, Centro, Rio de Janeiro", "https://facebook.com/VisitBrasil", "https://instagram.com/visitbrasil", "https://linkedin.com/company/visit-brasil", "https://twitter.com/VisitBrasil", "https://youtube.com/visitbrasil", "contato@visitbrasil.com", "+55-21-2212-0800", "https://www.visitbrasil.com/logo.png", "https://www.visitbrasil.com/bg.jpg", "https://maps.google.com/?q=-23.5505,-46.6333"],
    ["OF010", "Europe", "Italy", "Lazio", "Rome", "Italian National Tourist Board", "Tourism Board", "Official tourism board of Italy", "Showcasing Italy's art, culture, and cuisine", "https://www.italia.it", "Via Marghera 2, 00185 Roma", "https://facebook.com/ItaliaIT", "https://instagram.com/italia", "https://linkedin.com/company/enit", "https://twitter.com/Italia", "https://youtube.com/italia", "info@enit.it", "+39-06-49711", "https://www.italia.it/logo.svg", "https://www.italia.it/bg.jpg", "https://maps.google.com/?q=41.9028,12.4964"],
]

with open(r'c:\client work\directory-app\directory\office_data.csv', 'w', encoding='utf-8', newline='') as f:
    writer = csv.writer(f)
    writer.writerows(data)

print(f"CSV created with {len(data)-1} office records")
print("Fields include: Tourism Boards, Embassies, Government Offices")
print("All Google Maps links are properly quoted")
