import csv

data = [
    ["airline_id", "Continent", "Country", "Region", "City", "Name", "Info", "Description", "Website", "youtube", "Address", "Facebook", "Instagram", "LinkedIn", "Email", "Phone", "IATA", "ICAO", "Logo", "Background_Image", "Google_Maps_Link"],
    ["AL001", "North America", "USA", "California", "Los Angeles", "SkyWings Airlines", "Premium domestic flights", "Luxury air travel within the US", "https://skywings.com", "https://youtube.com/skywings", "123 Sky Blvd, LA, CA", "https://facebook.com/skywings", "https://instagram.com/skywings_air", "https://linkedin.com/company/skywings", "contact@skywings.com", "-1455", "SW", "SKW", "https://logos.skywings.com/logo.png", "https://bgs.skywings.com/airport.jpg", "https://maps.google.com/?q=34.0522,-118.2437"],
    ["AL002", "Europe", "Germany", "Bavaria", "Munich", "Lufthansa Wings", "Flag carrier subsidiary", "Regional flights across Europe", "https://lufthansa-wings.de", "https://youtube.com/lufthansawings", "Flughafenstrasse 1, Munich", "https://facebook.com/lufthansawings", "https://instagram.com/lhwings", "https://linkedin.com/company/lufthansawings", "info@lufthansa-wings.de", "-12345718", "LW", "LHW", "https://logos.lufthansa-wings.de/logo.png", "https://bgs.lufthansa-wings.de/runway.jpg", "https://maps.google.com/?q=48.1351,11.582"],
    ["AL003", "Asia", "Japan", "Kanto", "Tokyo", "Sakura Air", "Cherry blossom themed flights", "Experience Japan in the skies", "https://sakuraair.co.jp", "https://youtube.com/sakuraair_jp", "Haneda Airport Terminal 2", "https://facebook.com/sakuraair", "https://instagram.com/flysakura", "https://linkedin.com/company/sakura-air", "reservations@sakuraair.co.jp", "-15230", "SA", "SKR", "https://logos.sakuraair.co.jp/logo.png", "https://bgs.sakuraair.co.jp/cherry.jpg", "https://maps.google.com/?q=35.6895,139.6917"],
    ["AL004", "Africa", "Kenya", "Nairobi Region", "Nairobi", "Safari Skies", "Wildlife-inspired airline", "Fly over Africa in comfort", "https://safariskies.aero", "https://youtube.com/safariskies", "Jomo Kenyatta Intl Airport", "https://facebook.com/safariskies", "https://instagram.com/safariskies", "https://linkedin.com/company/safariskies", "bookings@safariskies.aero", "-557", "SS", "SAF", "https://logos.safariskies.aero/logo.png", "https://bgs.safariskies.aero/savanna.jpg", "https://maps.google.com/?q=-1.2921,36.8219"],
    ["AL005", "South America", "Brazil", "São Paulo", "São Paulo", "Tropical Airways", "Rainforest routes", "Connecting the Amazon", "https://tropicalairways.br", "https://youtube.com/tropicalairways", "Aeroporto de Congonhas", "https://facebook.com/tropicalairways", "https://instagram.com/tropical_air", "https://linkedin.com/company/tropicalairways", "contato@tropicalairways.br", "-12340", "TA", "TRP", "https://logos.tropicalairways.br/logo.png", "https://bgs.tropicalairways.br/jungle.jpg", "https://maps.google.com/?q=-23.5505,-46.6333"],
    ["AL006", "Australia", "Australia", "New South Wales", "Sydney", "Outback Air", "Interior connections", "Linking Australia's heartland", "https://outbackair.au", "https://youtube.com/outbackair", "Kingsford Smith Airport", "https://facebook.com/outbackair", "https://instagram.com/outback_air", "https://linkedin.com/company/outbackair", "info@outbackair.au", "-12360", "OA", "OUT", "https://logos.outbackair.au/logo.png", "https://bgs.outbackair.au/desert.jpg", "https://maps.google.com/?q=-33.8688,151.2093"],
    ["AL007", "North America", "Canada", "Ontario", "Toronto", "Maple Leaf Express", "Cross-Canada connections", "Experience Canada's diversity", "https://mapleleafexpress.ca", "https://youtube.com/mapleleafexpress", "100 Front Street, Toronto", "https://facebook.com/mapleleafexpress", "https://instagram.com/maple_express", "https://linkedin.com/company/mapleleafexpress", "bookings@mapleleafexpress.ca", "-14165", "ML", "MPL", "https://logos.mapleleafexpress.ca/logo.png", "https://bgs.mapleleafexpress.ca/mountains.jpg", "https://maps.google.com/?q=43.6426,-79.3871"],
    ["AL008", "Asia", "China", "Beijing", "Beijing", "Dragon Wings", "Modern China aviation", "Connecting the Middle Kingdom", "https://dragonwings.cn", "https://youtube.com/dragonwings", "Capital International Airport", "https://facebook.com/dragonwings", "https://instagram.com/dragon_wings", "https://linkedin.com/company/dragonwings", "service@dragonwings.cn", "-8610", "DW", "DRG", "https://logos.dragonwings.cn/logo.png", "https://bgs.dragonwings.cn/greatwall.jpg", "https://maps.google.com/?q=39.9042,116.4074"],
    ["AL009", "Europe", "France", "Île-de-France", "Paris", "Riviera Wings", "Mediterranean focus", "Luxury coastal flights", "https://rivierawings.fr", "https://youtube.com/rivierawings", "Charles de Gaulle Airport", "https://facebook.com/rivierawings", "https://instagram.com/riviera_air", "https://linkedin.com/company/rivierawings", "contact@rivierawings.fr", "-1402", "RW", "RVR", "https://logos.rivierawings.fr/logo.png", "https://bgs.rivierawings.fr/coastline.jpg", "https://maps.google.com/?q=48.8566,2.3522"],
    ["AL010", "Asia", "UAE", "Dubai", "Dubai", "Desert Falcon", "Premium Gulf carrier", "Experience Arabian hospitality", "https://desertfalcon.ae", "https://youtube.com/desertfalcon", "Dubai International Airport", "https://facebook.com/desertfalcon", "https://instagram.com/desert_falcon", "https://linkedin.com/company/desertfalcon", "reservations@desertfalcon.ae", "-9714", "DF", "DSF", "https://logos.desertfalcon.ae/logo.png", "https://bgs.desertfalcon.ae/skyline.jpg", "https://maps.google.com/?q=25.2048,55.2708"],
    ["AL011", "North America", "Mexico", "Mexico City", "Mexico City", "Aztec Air", "Cultural heritage flights", "Celebrating Mexican aviation", "https://aztecair.mx", "https://youtube.com/aztecair", "Benito Juárez International", "https://facebook.com/aztecair", "https://instagram.com/aztec_airways", "https://linkedin.com/company/aztecair", "info@aztecair.mx", "-5255", "AZ", "AZT", "https://logos.aztecair.mx/logo.png", "https://bgs.aztecair.mx/pyramid.jpg", "https://maps.google.com/?q=19.4326,-99.1332"],
    ["AL012", "Europe", "Italy", "Lazio", "Rome", "Mediterranean Express", "Italian hospitality", "Connecting Europe's south", "https://medexpress.it", "https://youtube.com/medexpress", "Fiumicino Airport", "https://facebook.com/medexpress", "https://instagram.com/med_express", "https://linkedin.com/company/medexpress", "prenotazioni@medexpress.it", "-396", "ME", "MED", "https://logos.medexpress.it/logo.png", "https://bgs.medexpress.it/colosseum.jpg", "https://maps.google.com/?q=41.9028,12.4964"],
    ["AL013", "Asia", "India", "Maharashtra", "Mumbai", "Bollywood Wings", "Entertainment airline", "Fly Bollywood style", "https://bollywoodwings.in", "https://youtube.com/bollywoodwings", "Chhatrapati Shivaji Intl", "https://facebook.com/bollywoodwings", "https://instagram.com/bollywood_air", "https://linkedin.com/company/bollywoodwings", "contact@bollywoodwings.in", "-9122", "BW", "BLW", "https://logos.bollywoodwings.in/logo.png", "https://bgs.bollywoodwings.in/mumbai.jpg", "https://maps.google.com/?q=19.076,72.8777"],
    ["AL014", "Africa", "South Africa", "Gauteng", "Johannesburg", "Rainbow Routes", "Unity in diversity", "Connecting Southern Africa", "https://rainbowroutes.za", "https://youtube.com/rainbowroutes", "OR Tambo International", "https://facebook.com/rainbowroutes", "https://instagram.com/rainbow_routes", "https://linkedin.com/company/rainbowroutes", "info@rainbowroutes.za", "-2711", "RR", "RNB", "https://logos.rainbowroutes.za/logo.png", "https://bgs.rainbowroutes.za/savanna.jpg", "https://maps.google.com/?q=-26.2041,28.0473"],
    ["AL015", "South America", "Argentina", "Buenos Aires", "Buenos Aires", "Tango Airways", "Dance-inspired service", "South American passion", "https://tangoairways.ar", "https://youtube.com/tangoairways", "Ministro Pistarini Intl", "https://facebook.com/tangoairways", "https://instagram.com/tango_air", "https://linkedin.com/company/tangoairways", "reservas@tangoairways.ar", "-5411", "TG", "TAN", "https://logos.tangoairways.ar/logo.png", "https://bgs.tangoairways.ar/buenosaires.jpg", "https://maps.google.com/?q=-34.6037,-58.3816"],
    ["AL016", "Europe", "Spain", "Madrid", "Madrid", "Iberian Express", "Peninsula connections", "Spanish hospitality", "https://iberianexpress.es", "https://youtube.com/iberianexpress", "Madrid-Barajas Airport", "https://facebook.com/iberianexpress", "https://instagram.com/iberian_express", "https://linkedin.com/company/iberianexpress", "contacto@iberianexpress.es", "-3491", "IE", "IBR", "https://logos.iberianexpress.es/logo.png", "https://bgs.iberianexpress.es/plaza.jpg", "https://maps.google.com/?q=40.4168,-3.7038"],
    ["AL017", "Asia", "Singapore", "Central", "Singapore", "Lion City Air", "Asian hub carrier", "Connecting Southeast Asia", "https://lioncityair.sg", "https://youtube.com/lioncityair", "Changi Airport Terminal 3", "https://facebook.com/lioncityair", "https://instagram.com/lioncity_air", "https://linkedin.com/company/lioncityair", "bookings@lioncityair.sg", "-656", "LC", "LCA", "https://logos.lioncityair.sg/logo.png", "https://bgs.lioncityair.sg/marina.jpg", "https://maps.google.com/?q=1.3521,103.8198"],
    ["AL018", "North America", "USA", "Illinois", "Chicago", "Great Lakes Airlines", "Midwest focus", "Regional excellence", "https://greatlakesair.com", "https://youtube.com/greatlakesair", "O'Hare Terminal 1, Chicago", "https://facebook.com/greatlakesair", "https://instagram.com/greatlakes_air", "https://linkedin.com/company/greatlakesair", "info@greatlakesair.com", "-1773", "GL", "GLA", "https://logos.greatlakesair.com/logo.png", "https://bgs.greatlakesair.com/skyline.jpg", "https://maps.google.com/?q=41.8781,-87.6298"],
    ["AL019", "Europe", "UK", "England", "London", "Thames Express", "British traditions", "Quintessentially British", "https://thamesexpress.uk", "https://youtube.com/thamesexpress", "Heathrow Terminal 5", "https://facebook.com/thamesexpress", "https://instagram.com/thames_express", "https://linkedin.com/company/thamesexpress", "enquiries@thamesexpress.uk", "-4420", "TE", "THM", "https://logos.thamesexpress.uk/logo.png", "https://bgs.thamesexpress.uk/bigben.jpg", "https://maps.google.com/?q=51.5074,-0.1278"],
    ["AL020", "Asia", "Thailand", "Bangkok", "Bangkok", "Orchid Airways", "Thai hospitality", "Land of smiles aviation", "https://orchidairways.th", "https://youtube.com/orchidairways", "Suvarnabhumi Airport", "https://facebook.com/orchidairways", "https://instagram.com/orchid_airways", "https://linkedin.com/company/orchidairways", "contact@orchidairways.th", "-662", "OD", "ORC", "https://logos.orchidairways.th/logo.png", "https://bgs.orchidairways.th/temple.jpg", "https://maps.google.com/?q=13.7563,100.5018"],
    ["AL021", "Oceania", "New Zealand", "Auckland", "Auckland", "Kiwi Connect", "Island hopping specialists", "Exploring Aotearoa", "https://kiwiconnect.nz", "https://youtube.com/kiwiconnect", "Auckland Airport", "https://facebook.com/kiwiconnect", "https://instagram.com/kiwi_connect", "https://linkedin.com/company/kiwiconnect", "bookings@kiwiconnect.nz", "-649", "KC", "KWI", "https://logos.kiwiconnect.nz/logo.png", "https://bgs.kiwiconnect.nz/mountains.jpg", "https://maps.google.com/?q=-36.8485,174.7633"],
    ["AL022", "Middle East", "Israel", "Tel Aviv", "Tel Aviv", "Desert Star", "Mediterranean meets Middle East", "Innovation in aviation", "https://desertstar.il", "https://youtube.com/desertstar", "Ben Gurion Airport", "https://facebook.com/desertstar", "https://instagram.com/desert_star", "https://linkedin.com/company/desertstar", "info@desertstar.il", "-9723", "DS", "DST", "https://logos.desertstar.il/logo.png", "https://bgs.desertstar.il/telaviv.jpg", "https://maps.google.com/?q=32.0853,34.7818"],
    ["AL023", "Asia", "South Korea", "Seoul", "Seoul", "Seoul Sky", "K-pop inspired", "Modern Korean aviation", "https://seoulsky.kr", "https://youtube.com/seoulsky", "Incheon International", "https://facebook.com/seoulsky", "https://instagram.com/seoul_sky", "https://linkedin.com/company/seoulsky", "contact@seoulsky.kr", "-822", "SK", "SEO", "https://logos.seoulsky.kr/logo.png", "https://bgs.seoulsky.kr/seoul.jpg", "https://maps.google.com/?q=37.5665,126.978"],
    ["AL024", "Europe", "Netherlands", "North Holland", "Amsterdam", "Tulip Air", "Dutch efficiency", "Connecting Europe's heart", "https://tulipair.nl", "https://youtube.com/tulipair", "Schiphol Airport", "https://facebook.com/tulipair", "https://instagram.com/tulip_airways", "https://linkedin.com/company/tulipair", "service@tulipair.nl", "-3120", "TU", "TLP", "https://logos.tulipair.nl/logo.png", "https://bgs.tulipair.nl/windmill.jpg", "https://maps.google.com/?q=52.3676,4.9041"],
    ["AL025", "North America", "USA", "New York", "New York", "Empire State Air", "East Coast premier", "NYC and beyond", "https://empirestateair.com", "https://youtube.com/empirestateair", "JFK Terminal 4, NY", "https://facebook.com/empirestateair", "https://instagram.com/empire_air", "https://linkedin.com/company/empirestateair", "reservations@empirestateair.com", "-1212", "ES", "EMP", "https://logos.empirestateair.com/logo.png", "https://bgs.empirestateair.com/manhattan.jpg", "https://maps.google.com/?q=40.7128,-74.006"],
    ["AL026", "Asia", "Malaysia", "Kuala Lumpur", "Kuala Lumpur", "Petronas Wings", "Twin tower inspired", "Malaysian excellence", "https://petronaswings.my", "https://youtube.com/petronaswings", "KLIA Terminal 1", "https://facebook.com/petronaswings", "https://instagram.com/petronas_wings", "https://linkedin.com/company/petronaswings", "info@petronaswings.my", "-603", "PW", "PTR", "https://logos.petronaswings.my/logo.png", "https://bgs.petronaswings.my/towers.jpg", "https://maps.google.com/?q=3.139,101.6869"],
]

with open(r'c:\client work\directory-app\directory\airline_details_dummy.csv', 'w', encoding='utf-8', newline='') as f:
    writer = csv.writer(f)
    writer.writerows(data)

print(f"CSV created with {len(data)-1} airline records")
